version: '3.7'

networks:
    default:
         name: YourNetworkName
         external: true

services:
    you2me:
        container_name: You2Me
        stdin_open: true
        tty: true
        image: you2me:latest
        hostname: You2Me
        networks: 
            - default
        ports:
            - 80:80
        restart: always

